SELECT CE.COD_LOCAL, IE.COD_ITEM, IE.DES_ITEM, CE.COD_UNIDADE, SUM(CE.QTD_ENTRADA-CE.QTD_SAIDA)
FROM CE_LOCAIS_ENTRADA CE, IE_ITENS IE
WHERE CE.COD_UNIDADE = 12
AND CE.COD_ITEM = IE.COD_ITEM
AND CE.QTD_ENTRADA-CE.QTD_SAIDA > 0
GROUP BY CE.COD_LOCAL, IE.COD_ITEM, IE.DES_ITEM, CE.COD_UNIDADE
ORDER BY 1
